In [39]:
#importando biblioteca pandas
import pandas as pd

In [40]:
#lendo o arquivo CSV
phones = pd.read_csv('smartphones.csv')

In [41]:
#imprime o cabeçalho do database
phones.head()

,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,231.60
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,279.00
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,179.01
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,279.99
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00

Adicionar nova coluna "category"

In [42]:
#cria a coluna "category", aplicando diferentes labels de acordo com o preço do smartphone, utilizando a função lambda 
phones['Category'] = phones.apply(
    lambda row: "Flagship" if row['Final Price'] >= 699 else 
                "Mid-range" if (row['Final Price'] < 699) & (row['Final Price'] >= 299) else  
                "Budget" if row['Final Price'] < 299 else 
                "unknown", axis=1
)

In [43]:
#imprime as colunas do database (agora com 'category')
print(phones.columns)

Index(['Smartphone', 'Brand', 'Model', 'RAM', 'Storage', 'Color', 'Free',
       'Final Price', 'Category'],
      dtype='object')

In [44]:
#imprime o cabeçalho do database
phones.head()

,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price,Category
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,231.60,Budget
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,279.00,Budget
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,179.01,Budget
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,279.99,Budget
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00,Flagship

Tratando dados nulos

In [45]:
#retorna a soma de todos os resultados nulos para cada coluna
phones.isnull().sum()

Smartphone       0
Brand            0
Model            0
RAM            483
Storage         25
Color            0
Free             0
Final Price      0
Category         0
dtype: int64

In [46]:
#remove todas as linhas com dados nulos e aplica definitivamente
phones.dropna(inplace=True)

In [47]:
#retorna a soma de todos os resultados nulos para cada coluna
phones.isnull().sum()

Smartphone     0
Brand          0
Model          0
RAM            0
Storage        0
Color          0
Free           0
Final Price    0
Category       0
dtype: int64

Adicionar coluna "description"

In [48]:
#cria a coluna 'Description' que soma uma série de colunas e strings
phones['Description'] = phones['Brand'] + " " + phones['Model'] + " with " + phones['RAM'].astype(int).astype(str) + "GB of RAM and " + phones['Storage'].astype(int).astype(str) + "GB of storage in the " + phones['Color'] + " Color"

In [49]:
#imprime o cabeçalho do dataframe
phones.head()

,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price,Category,Description
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,231.60,Budget,Realme C55 with 8GB of RAM and 256GB of storag...
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,279.00,Budget,Samsung Galaxy M23 with 4GB of RAM and 128GB o...
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,179.01,Budget,Motorola Moto G13 with 4GB of RAM and 128GB of...
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,279.99,Budget,Xiaomi Redmi Note 11S with 6GB of RAM and 128G...
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00,Flagship,Nothing Phone (2) with 12GB of RAM and 512GB o...

In [50]:
#soma de celulares na categoria 'budget'
len(phones.query("Category == 'Budget'"))

699

In [51]:
#soma de celulares na categoria 'mid-range'
len(phones.query("Category == 'Mid-range'"))

475

In [52]:
#soma de celulares na categoria 'Flagship'
len(phones.query("Category == 'Flagship'"))

159

Média dos preços

In [53]:
#imprime a média arredondada do preço final dos smartphones
round(phones['Final Price'].mean(), 2)

380.27

Celulares com maior capacidade de armazenamento

In [54]:
#atribui a uma variável o(s) celulares com a maior capacidade de armazenamento
maior_armazenamento = phones['Storage'].max()

In [55]:
#retorna todos os celulares com esse armazenamento (512gb)
maiores_armazenamentos = phones.query("Storage == @maior_armazenamento")
maiores_armazenamentos

,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price,Category,Description
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00,Flagship,Nothing Phone (2) with 12GB of RAM and 512GB o...
32,Realme 11 Pro Plus 5G 12/512GB Amoled FHD+ Cur...,Realme,11 Pro,12.0,512.0,White,Yes,521.60,Mid-range,Realme 11 Pro with 12GB of RAM and 512GB of st...
43,Realme 11 Pro Plus 5G 12/512GB Amoled FHD+ Cur...,Realme,11 Pro,12.0,512.0,Black,Yes,521.60,Mid-range,Realme 11 Pro with 12GB of RAM and 512GB of st...
95,Nothing Phone (2) 12/512GB Gris Oscuro Libre,Nothing,Phone (2),12.0,512.0,Gray,Yes,799.00,Flagship,Nothing Phone (2) with 12GB of RAM and 512GB o...
477,Samsung Galaxy Z Fold4 12/512GB Negro Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Black,Yes,1919.00,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...
661,Samsung Galaxy Z Fold4 12/512GB Verde Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Green,Yes,1919.00,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...
753,Samsung Galaxy Z Fold4 12/512GB Negro Libre,Samsung,Galaxy Z Fold4,12.0,512.0,Black,Yes,1495.00,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...
983,Samsung Galaxy Z Fold4 12/512GB Negro Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Black,Yes,1922.93,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...
1106,Samsung Galaxy Z Flip4 8/512GB Gris Libre,Samsung,Galaxy Z Flip4,8.0,512.0,Gray,Yes,797.00,Flagship,Samsung Galaxy Z Flip4 with 8GB of RAM and 512...
1225,Oppo Find X2 Pro 12/512GB Negro Libre,OPPO,X2,12.0,512.0,Black,Yes,327.99,Mid-range,OPPO X2 with 12GB of RAM and 512GB of storage ...
1456,Oppo Find X2 Pro 12/512GB Naranja Libre,OPPO,X2,12.0,512.0,Orange,Yes,670.07,Mid-range,OPPO X2 with 12GB of RAM and 512GB of storage ...
1579,Samsung Galaxy S22 Ultra 5G 12/512GB Negro Libre,Samsung,Galaxy S22,12.0,512.0,Black,Yes,1625.36,Flagship,Samsung Galaxy S22 with 12GB of RAM and 512GB ...
1580,Samsung Galaxy S22 Ultra 5G 12/512GB Verde Libre,Samsung,Galaxy S22,12.0,512.0,Green,Yes,1688.53,Flagship,Samsung Galaxy S22 with 12GB of RAM and 512GB ...
1603,Samsung Galaxy Z Flip4 8/512GB Azul Libre Vers...,Samsung,Galaxy Z Flip4,8.0,512.0,Blue,Yes,1169.66,Flagship,Samsung Galaxy Z Flip4 with 8GB of RAM and 512...
1604,Samsung Galaxy Z Flip4 8/512GB Gris Libre Vers...,Samsung,Galaxy Z Flip4,8.0,512.0,Gray,Yes,1172.70,Flagship,Samsung Galaxy Z Flip4 with 8GB of RAM and 512...
1794,Samsung Galaxy Z Fold4 12/512GB Verde Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Green,Yes,1922.93,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...

Custo por GB de armazenamento

In [56]:
#cria uma coluna 'price por GB, mapeando todas as linhas para definir o custo por GB de cada celular
phones['Price per GB'] = phones.apply(lambda row: row["Final Price"] / row['Storage'], axis=1)

In [57]:
#ordena o dataframe pelo preço por GB
phones.sort_values(by='Price per GB')

,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price,Category,Description,Price per GB
1225,Oppo Find X2 Pro 12/512GB Negro Libre,OPPO,X2,12.0,512.0,Black,Yes,327.99,Mid-range,OPPO X2 with 12GB of RAM and 512GB of storage ...,0.640605
748,Oppo Find X2 Neo 12/256GB 5G Negro Libre,OPPO,Find X2 Neo,12.0,256.0,Black,Yes,189.00,Budget,OPPO Find X2 Neo with 12GB of RAM and 256GB of...,0.738281
1237,Oppo Find X2 Neo 12/256GB 5G Azul Libre,OPPO,Find X2 Neo,12.0,256.0,Blue,Yes,189.00,Budget,OPPO Find X2 Neo with 12GB of RAM and 256GB of...,0.738281
1011,Oppo Reno 2 8/256GB Luminous Black Libre,OPPO,Reno 2,8.0,256.0,Black,Yes,198.00,Budget,OPPO Reno 2 with 8GB of RAM and 256GB of stora...,0.773438
269,TCL 40 SE 6/256GB Púrpura Libre,TCL,40 SE,6.0,256.0,Purple,Yes,200.99,Budget,TCL 40 SE with 6GB of RAM and 256GB of storage...,0.785117
...,...,...,...,...,...,...,...,...,...,...,...
1328,Crosscall CORE-M5 3/32GB Negro Libre,Crosscall,CORE-M5,3.0,32.0,Black,Yes,410.00,Mid-range,Crosscall CORE-M5 with 3GB of RAM and 32GB of ...,12.812500
1351,Funker W5.5 Pro 2/16GB Azul,Funker,W5.5,2.0,16.0,Blue,No,220.78,Budget,Funker W5.5 with 2GB of RAM and 16GB of storag...,13.798750
1330,Crosscall Core-X4 3/32GB Libre,Crosscall,Core-X4,3.0,32.0,Black,Yes,487.09,Mid-range,Crosscall Core-X4 with 3GB of RAM and 32GB of ...,15.221562
1362,Hammer Explorer 3/32GB Negro/Naranja Libre,Hammer,Explorer,3.0,32.0,Orange,Yes,528.46,Mid-range,Hammer Explorer with 3GB of RAM and 32GB of st...,16.514375
1284,Nokia 5.4 4/64GB Noche Polar Libre Versión Imp...,Nokia,5.4,4.0,64.0,Black,Yes,1499.00,Flagship,Nokia 5.4 with 4GB of RAM and 64GB of storage ...,23.421875

Ordenar por preço e filtrar por marca

In [58]:
#ordenando por preço
phones.sort_values(by='Final Price')

,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price,Category,Description,Price per GB
1052,SPC Smart 2 1/16GB Rojo Libre,SPC,Smart 2,1.0,16.0,Red,Yes,70.68,Budget,SPC Smart 2 with 1GB of RAM and 16GB of storag...,4.417500
109,Alcatel 1 (2021) 1/16GB Negro Libre,Alcatel,1 (2021),1.0,16.0,Black,Yes,70.98,Budget,Alcatel 1 (2021) with 1GB of RAM and 16GB of s...,4.436250
108,Alcatel 1 (2021) 1/16GB Azul Libre,Alcatel,1 (2021),1.0,16.0,Blue,Yes,70.98,Budget,Alcatel 1 (2021) with 1GB of RAM and 16GB of s...,4.436250
376,Xiaomi Redmi A2 2/32GB Verde Claro Libre,Xiaomi,Redmi A2,2.0,32.0,Green,Yes,77.98,Budget,Xiaomi Redmi A2 with 2GB of RAM and 32GB of st...,2.436875
536,Xiaomi Redmi A2 2/32GB Azul Claro Libre,Xiaomi,Redmi A2,2.0,32.0,Blue,Yes,79.99,Budget,Xiaomi Redmi A2 with 2GB of RAM and 32GB of st...,2.499687
...,...,...,...,...,...,...,...,...,...,...,...
477,Samsung Galaxy Z Fold4 12/512GB Negro Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Black,Yes,1919.00,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...,3.748047
661,Samsung Galaxy Z Fold4 12/512GB Verde Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Green,Yes,1919.00,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...,3.748047
983,Samsung Galaxy Z Fold4 12/512GB Negro Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Black,Yes,1922.93,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...,3.755723
1794,Samsung Galaxy Z Fold4 12/512GB Verde Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Green,Yes,1922.93,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...,3.755723
1380,Honor Magic4 Pro 5G 8/256GB Cian Libre,Honor,Magic4,8.0,256.0,Turquoise,Yes,2271.28,Flagship,Honor Magic4 with 8GB of RAM and 256GB of stor...,8.872188

In [59]:
#filtrando por marca e então ordenando por preço
phones.query("Brand == 'Samsung'").sort_values(by='Final Price')

,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price,Category,Description,Price per GB
1766,Samsung Galaxy A10 2/32GB Rojo Libre Versión I...,Samsung,Galaxy A10,2.0,32.0,Red,Yes,95.00,Budget,Samsung Galaxy A10 with 2GB of RAM and 32GB of...,2.968750
1171,Samsung Galaxy A20e 3/32GB Azul Libre,Samsung,Galaxy A20e,3.0,32.0,Blue,Yes,99.99,Budget,Samsung Galaxy A20e with 3GB of RAM and 32GB o...,3.124687
455,Samsung Galaxy A20e 3/32GB Negro Libre,Samsung,Galaxy A20e,3.0,32.0,Black,Yes,105.00,Budget,Samsung Galaxy A20e with 3GB of RAM and 32GB o...,3.281250
876,Samsung Galaxy A40 4/64GB Negro Libre Versión ...,Samsung,Galaxy A40,4.0,64.0,Black,Yes,120.00,Budget,Samsung Galaxy A40 with 4GB of RAM and 64GB of...,1.875000
1265,Samsung Galaxy A40 4/64GB Azul Libre Versión I...,Samsung,Galaxy A40,4.0,64.0,Blue,Yes,120.00,Budget,Samsung Galaxy A40 with 4GB of RAM and 64GB of...,1.875000
...,...,...,...,...,...,...,...,...,...,...,...
1293,Samsung Galaxy Z Fold4 12/256GB Verde Libre + ...,Samsung,Galaxy Z Fold4,12.0,256.0,Green,Yes,1802.94,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 25...,7.042734
661,Samsung Galaxy Z Fold4 12/512GB Verde Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Green,Yes,1919.00,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...,3.748047
477,Samsung Galaxy Z Fold4 12/512GB Negro Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Black,Yes,1919.00,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...,3.748047
983,Samsung Galaxy Z Fold4 12/512GB Negro Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Black,Yes,1922.93,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...,3.755723
1794,Samsung Galaxy Z Fold4 12/512GB Verde Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Green,Yes,1922.93,Flagship,Samsung Galaxy Z Fold4 with 12GB of RAM and 51...,3.755723

Calcular a Porcentagem de Smartphones com maior armazenamento

In [60]:
#atribui a uma variavel a soma dos celulares com o maior armazenamento (512gb)
soma_maiores_armazenamentos = maiores_armazenamentos.count()['Smartphone']

In [61]:
#atribui a uma variavel a soma de todos os celulares
total_celulares = phones.count()['Smartphone']

In [62]:
#calcula o percentual dos celulares com maior armazenamento com o total de celulares
percentual = (soma_maiores_armazenamentos/total_celulares) * 100

In [63]:
#imprime o percentual arredondado
round(percentual, 2)

1.2

Calcular a porcentagem de smartphones com 64gb

In [64]:
#imprime todos os celulares com 64gb de armazenamento
celulares_64gb = phones.query("Storage == 64")

In [65]:
#atribui a uma variável a soma de todos esses celulares e imprime
soma_celulares_64gb = celulares_64gb.count()['Smartphone']
soma_celulares_64gb

260

In [66]:
#atribui a uma variável o percentual dos celulares com 64gb em relação ao total de celulares
percentual = (soma_celulares_64gb/total_celulares) * 100

In [67]:
#imprime o percentual arredondado
round(percentual, 2)

19.5

percentual de celulares de cada categoria

In [68]:
#atribui a uma variavel o total de celulares na categoria 'budget'
celulares_baratos = len(phones.query("Category == 'Budget'"))
celulares_baratos

699

In [69]:
#atribui a uma variavel o total de celulares na categoria 'mid-range'
celulares_medios = len(phones.query("Category == 'Mid-range'"))
celulares_medios

475

In [70]:
#atribui a uma variavel o total de celulares na categoria 'flagship'
celulares_caros = len(phones.query("Category == 'Flagship'"))
celulares_caros

159

In [71]:
#atribui a uma variável a relação de celulares budget em comparação com o total e imprime o valor arredondado
relacao_baratos = (celulares_baratos/total_celulares) * 100
round(relacao_baratos, 2)

52.44

In [72]:
#atribui a uma variável a relação de celulares mid-range em comparação com o total e imprime o valor arredondado
relacao_medios = (celulares_medios/total_celulares) * 100
round(relacao_medios, 2)

35.63

In [73]:
#atribui a uma variável a relação de celulares flagship em comparação com o total e imprime o valor arredondado
relacao_caros = (celulares_caros/total_celulares) * 100
round(relacao_caros, 2)

11.93

Salvando a nova base de dados

In [76]:
#importa a base de dados 'phones' para um novo arquivo CSV
phones.to_csv('smartphones_enhanced.csv')

In [77]:
#faz a leitura do novo arquivo CSV 
pd.read_csv('smartphones_enhanced.csv')

,Unnamed: 0,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price,Category,Description,Price per GB
0,0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,231.60,Budget,Realme C55 with 8GB of RAM and 256GB of storag...,0.904687
1,1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,279.00,Budget,Samsung Galaxy M23 with 4GB of RAM and 128GB o...,2.179688
2,2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,179.01,Budget,Motorola Moto G13 with 4GB of RAM and 128GB of...,1.398516
3,3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,279.99,Budget,Xiaomi Redmi Note 11S with 6GB of RAM and 128G...,2.187422
4,4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00,Flagship,Nothing Phone (2) with 12GB of RAM and 512GB o...,1.560547
...,...,...,...,...,...,...,...,...,...,...,...,...
1328,1811,Xiaomi Redmi Note 8 4/64GB Azul Libre,Xiaomi,Redmi Note 8,4.0,64.0,Blue,Yes,249.01,Budget,Xiaomi Redmi Note 8 with 4GB of RAM and 64GB o...,3.890781
1329,1812,Xiaomi Redmi Note 8T 4/128GB Azul Estelar Libre,Xiaomi,Redmi Note 8T,4.0,128.0,Blue,Yes,200.00,Budget,Xiaomi Redmi Note 8T with 4GB of RAM and 128GB...,1.562500
1330,1813,Xiaomi Redmi Note 9 4/128GB Blanco Libre,Xiaomi,Redmi Note 9,4.0,128.0,White,Yes,269.00,Budget,Xiaomi Redmi Note 9 with 4GB of RAM and 128GB ...,2.101562
1331,1814,Xiaomi Redmi Note 9S 4/64GB Dual SIM Gris Libre,Xiaomi,Note 9S,4.0,64.0,Gray,Yes,211.00,Budget,Xiaomi Note 9S with 4GB of RAM and 64GB of sto...,3.296875
1332,1815,Xiaomi Redmi Note 9S 6/128GB Dual SIM Gris Libre,Xiaomi,Note 9S,6.0,128.0,Gray,Yes,289.00,Budget,Xiaomi Note 9S with 6GB of RAM and 128GB of st...,2.257812